packages:
  - ansible
  - baobab
  - base
  - base-devel
  - bash-completion
  - bat
  - docker
  - epiphany
  - evince
  - falkon
  - fd
  - firefox
  - fzf
  - gdm
  - ghostty
  - git
  - gnome-backgrounds
  - gnome-calculator
  - gnome-calendar
  - gnome-characters
  - gnome-clocks
  - gnome-color-manager
  - gnome-connections
  - gnome-console
  - gnome-contacts
  - gnome-control-center
  - gnome-disk-utility
  - gnome-font-viewer
  - gnome-keyring
  - gnome-logs
  - gnome-maps
  - gnome-menus
  - gnome-music
  - gnome-remote-desktop
  - gnome-session
  - gnome-settings-daemon
  - gnome-shell
  - gnome-shell-extensions
  - gnome-software
  - gnome-system-monitor
  - gnome-text-editor
  - gnome-tour
  - gnome-user-docs
  - gnome-user-share
  - gnome-weather
  - go
  - gopls
  - grilo-plugins
  - grub
  - gst-plugin-pipewire
  - gvfs
  - gvfs-afc
  - gvfs-dnssd
  - gvfs-goa
  - gvfs-google
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-onedrive
  - gvfs-smb
  - gvfs-wsdd
  - intel-ucode
  - iwd
  - jq
  - lazygit
  - less
  - libpulse
  - linux
  - linux-firmware
  - loupe
  - lua-language-server
  - lximage-qt
  - lxqt-about
  - lxqt-admin
  - lxqt-archiver
  - lxqt-config
  - lxqt-globalkeys
  - lxqt-notificationd
  - lxqt-openssh-askpass
  - lxqt-panel
  - lxqt-policykit
  - lxqt-powermanagement
  - lxqt-qtplugin
  - lxqt-runner
  - lxqt-session
  - lxqt-sudo
  - lxqt-themes
  - malcontent
  - nautilus
  - neovim
  - networkmanager
  - nomad
  - npm
  - obconf-qt
  - openbox
  - orca
  - pavucontrol-qt
  - pcmanfm-qt
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - postgresql
  - pyright
  - qps
  - qterminal
  - ripgrep
  - rygel
  - screengrab
  - sddm
  - simple-scan
  - snapshot
  - stylua
  - sushi
  - tecla
  - tmux
  - totem
  - vagrant
  - vim
  - virtualbox
  - vivaldi
  - wget
  - wireplumber
  - xclip
  - xdg-desktop-portal-gnome
  - xdg-desktop-portal-lxqt
  - xdg-user-dirs-gtk
  - xorg-server
  - xorg-xinit
  - yelp
  - zellij
  - zig
  - zls
  - zram-generator
