---
- name: Install packages on Arch Linux
  hosts: all
  become: true
  tasks:
    - name: Load package list
      include_vars:
        file: "../config/package-list/package-list.yml"

    - name: Install packages
      pacman:
        name: "{{ packages }}"
        state: present
